/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramShop;

import java.awt.Toolkit;

/**
 *
 * @author DELL
 */
public class HelpMenu extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public HelpMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
           setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/hinh/a.png")));//set icon of frame
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblHelpTitle = new javax.swing.JLabel();
        pnlTextBackgr = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblProduct = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblBill = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblNewBill = new javax.swing.JLabel();
        lblHelp = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");

        pnlBackground.setBackground(new java.awt.Color(102, 102, 102));

        lblHelpTitle.setFont(new java.awt.Font("Elephant", 1, 50)); // NOI18N
        lblHelpTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblHelpTitle.setText("Help");

        pnlTextBackgr.setBackground(new java.awt.Color(197, 209, 197));

        jScrollPane1.setBackground(new java.awt.Color(197, 209, 197));
        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(197, 209, 197));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("After login, in menu shop\nplease choose one option:\n -Product management.\n -Employee management.\n -Customer management.\n -Bill management.\n -Account management.\n -Create new bill.\n - Help for how to use our program.\n - About for see information of our group.\n - Exit for close the program.");
        jTextArea1.setAlignmentX(1.0F);
        jTextArea1.setAlignmentY(1.0F);
        jTextArea1.setMargin(new java.awt.Insets(0, 5, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/products.png"))); // NOI18N

        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/employees.png"))); // NOI18N
        lblEmployee.setLabelFor(jTextArea1);

        lblCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/customers.png"))); // NOI18N

        lblBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/bills.png"))); // NOI18N

        lblAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/accounts.png"))); // NOI18N

        lblNewBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/billhelp.png"))); // NOI18N

        lblHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/help.png"))); // NOI18N

        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/about.png"))); // NOI18N

        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/exit.png"))); // NOI18N

        javax.swing.GroupLayout pnlTextBackgrLayout = new javax.swing.GroupLayout(pnlTextBackgr);
        pnlTextBackgr.setLayout(pnlTextBackgrLayout);
        pnlTextBackgrLayout.setHorizontalGroup(
            pnlTextBackgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextBackgrLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTextBackgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduct)
                    .addComponent(lblEmployee)
                    .addComponent(lblCustomer)
                    .addComponent(lblBill)
                    .addComponent(lblAccount)
                    .addComponent(lblNewBill)
                    .addComponent(lblHelp)
                    .addComponent(lblAbout)
                    .addComponent(lblExit))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        pnlTextBackgrLayout.setVerticalGroup(
            pnlTextBackgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextBackgrLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(lblProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewBill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/exit-93-458494.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(pnlTextBackgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(lblHelpTitle)
                        .addGap(359, 359, 359))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnExit)
                .addGap(1, 1, 1)
                .addComponent(lblHelpTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(pnlTextBackgr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblBill;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHelp;
    private javax.swing.JLabel lblHelpTitle;
    private javax.swing.JLabel lblNewBill;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlTextBackgr;
    // End of variables declaration//GEN-END:variables
}
