/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramShop;

import com.mysql.jdbc.Connection;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import shopmanage.ProductBrandInformation;
import shopmanage.ProductBrandModel;
import shopmanage.ProductInformation;
import shopmanage.ProductModel;
import shopmanage.ProductTypeInformation;
import shopmanage.ProductTypeModel;

/**
 *
 * @author DELL
 */
public class ProductMenu extends javax.swing.JFrame {

    //declare variables
    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<ProductInformation> pro = new ArrayList<>();//create new list product
    ProductModel pm;
    ProductTypeModel ptm;
    ProductBrandModel pbm;
    ArrayList<ProductBrandInformation> probrands = new ArrayList<>();
    ArrayList<ProductTypeInformation> protypes = new ArrayList<>();

    /**
     * Creates new form ProductMenu
     */
    public ProductMenu() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        dtm = (DefaultTableModel) this.tbProduct.getModel();
        pm = new ProductModel();
        ptm = new ProductTypeModel();
        pbm = new ProductBrandModel();
        tbProduct.getTableHeader().setFont(new Font("Tagoma", Font.CENTER_BASELINE, 20));//set font and size for table header
        tbProduct.setRowHeight(28);//set size for row
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/hinh/product.png")));//set icon for program
        loadData();//load data to table
    }

    public void loadData() {
        dtm.setRowCount(0);//set table row equal 0
        pro = new ArrayList<>();//create new list product
        try {
            pro = pm.loadProduct();//load product 
            probrands = pbm.loadProductBrand();//load product brand
            protypes = ptm.loadProductType();//load product type
            for (int i = 0; i < pro.size(); i++) {
                String type = ptm.findProductName(pro.get(i).getPtype());
                String brand = pbm.findProductName(pro.get(i).getBrand());
                Object[] row = {pro.get(i).getPid(), pro.get(i).getPname(), type, pro.get(i).getPrice(), pro.get(i).getSize(), brand};
                dtm.addRow(row);//add data to table row
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Can't load data.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAll = new javax.swing.JPanel();
        pnlTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        pnlInformation = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtPName = new javax.swing.JTextField();
        txtPPrice = new javax.swing.JTextField();
        txtPSize = new javax.swing.JTextField();
        txtPBrand = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox<>();
        txtPType = new javax.swing.JTextField();
        BrandCombo = new javax.swing.JComboBox<>();
        lblProductID = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        SizeCombo = new javax.swing.JComboBox<>();
        btnClear1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Product Menu");
        setResizable(false);

        pnlAll.setBackground(new java.awt.Color(102, 102, 102));

        pnlTable.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbProduct.setBackground(new java.awt.Color(197, 209, 197));
        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Product Type", "Product Price", "Product Size", "Product Brand"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduct);

        javax.swing.GroupLayout pnlTableLayout = new javax.swing.GroupLayout(pnlTable);
        pnlTable.setLayout(pnlTableLayout);
        pnlTableLayout.setHorizontalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlTableLayout.setVerticalGroup(
            pnlTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pnlInformation.setBackground(new java.awt.Color(197, 209, 197));
        pnlInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 0, 0));
        lblName.setText("Product Name");

        lblType.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 0, 0));
        lblType.setText("Product Type");

        lblPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblPrice.setText("Product Price");

        lblSize.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSize.setForeground(new java.awt.Color(0, 0, 0));
        lblSize.setText("Product Size");

        lblBrand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBrand.setForeground(new java.awt.Color(0, 0, 0));
        lblBrand.setText("Product Brand");

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/add (1).png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/exit-93-458494.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/update_png_1445289.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtPName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtPPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtPSize.setEditable(false);
        txtPSize.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtPBrand.setEditable(false);
        txtPBrand.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        TypeCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mì", "Phở", "Hủ Tiếu", "Nước ngọt" }));
        TypeCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboActionPerformed(evt);
            }
        });

        txtPType.setEditable(false);
        txtPType.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPTypeActionPerformed(evt);
            }
        });

        BrandCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BrandCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VietNam", "China", "Korea" }));
        BrandCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrandComboActionPerformed(evt);
            }
        });

        lblProductID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblProductID.setForeground(new java.awt.Color(0, 0, 0));
        lblProductID.setText("Product ID");

        txtPID.setEditable(false);
        txtPID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnEdit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/edit-png-icon-blue-pencil-18.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        SizeCombo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        SizeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Large" }));
        SizeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeComboActionPerformed(evt);
            }
        });

        btnClear1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/clear-512 (1).png"))); // NOI18N
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInformationLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblType)
                            .addComponent(lblSize)
                            .addComponent(lblBrand)
                            .addComponent(lblPrice)
                            .addComponent(lblProductID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BrandCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SizeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPSize, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(txtPBrand)))
                            .addComponent(txtPName)
                            .addGroup(pnlInformationLayout.createSequentialGroup()
                                .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPType, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                            .addComponent(txtPPrice)
                            .addComponent(txtPID)))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addComponent(btnClear1)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)))
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(31, 31, 31))
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPID, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(lblProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblType))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPrice)
                        .addComponent(txtPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlInformationLayout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addComponent(lblSize))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInformationLayout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SizeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPSize, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BrandCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblBrand))
                .addGap(41, 41, 41)
                .addGroup(pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnExit)
                    .addComponent(btnClear1))
                .addContainerGap())
        );

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitle.setText("Product Management");

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hinh/exit-93-458494.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAllLayout = new javax.swing.GroupLayout(pnlAll);
        pnlAll.setLayout(pnlAllLayout);
        pnlAllLayout.setHorizontalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAllLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAllLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogout)
                                .addContainerGap())
                            .addGroup(pnlAllLayout.createSequentialGroup()
                                .addComponent(pnlInformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(122, 122, 122))))
        );
        pnlAllLayout.setVerticalGroup(
            pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAllLayout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addComponent(pnlInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //TODO add your handling code here:
        boolean check = pm.checkName(txtPName.getText());
        try {
            if (txtPName.getText().equals("")) {//check name empty
                JOptionPane.showMessageDialog(this, "Product name can't be empty.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (check == true) {
                JOptionPane.showMessageDialog(this, "Product name is already in list product.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (txtPType.getText().equals("")) {//check type empty
                JOptionPane.showMessageDialog(this, "Product type can't be empty.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (Integer.parseInt(txtPPrice.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Product price must be greater than 0.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (txtPPrice.getText().equals("")) {//check price empty
                JOptionPane.showMessageDialog(this, "Product price can't be empty.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (txtPSize.getText().equals("")) {//check size empty
                JOptionPane.showMessageDialog(this, "Product size can't be empty.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else if (txtPBrand.getText().equals("")) {//check brand empty
                JOptionPane.showMessageDialog(this, "Product brand can't be empty.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
            } else {//check true
                String name = txtPName.getText();//get name
                String type = txtPType.getText();//get type
                int price = Integer.parseInt(txtPPrice.getText());//get price
                String size = txtPSize.getText();//get size
                String brand = txtPBrand.getText();//get brand
                int t = ptm.findIndexProduct(type);
                int b = pbm.findIndexProductByBrand(brand);
                try {
                    pm.insertProduct(name, price, size, t, b);//insert product to database
                    pro = pm.loadProduct();//load data to list product
                    loadData();//load to table
                    tbProduct.updateUI();//reset table
                    JOptionPane.showMessageDialog(this, "Add product successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);//display message

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Can't add product.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Can't add product.", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Number can't be number decimal .", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
        }
//        try {
//            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/shop_manage", "root", "");
//            PreparedStatement st = conn.prepareStatement("INSERT INTO `product` VALUES(?,?,?,?,?)");         
//            st.setString(2 , txtPName.getText());
//            st.setString(3, TypeCombo.getSelectedItem().toString());
//            st.setString(4, txtPPrice.getText());
//            st.setString(5, SizeCombo.getSelectedItem().toString());
//            st.setString(6, BrandCombo.getSelectedItem().toString());
//            if (st.executeUpdate() < 0) {
//                JOptionPane.showMessageDialog(this, "add erro");
//            } else {
//                JOptionPane.showMessageDialog(this, "add successfully!!");
//            }
//
//        } catch (Exception e) {
//        }


    }//GEN-LAST:event_btnAddActionPerformed
    /**
     * action when click clear button
     *
     * @param evt
     */
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            // TODO add your handling code here:
            pm.deleteProduct(Integer.parseInt(txtPID.getText()));
            loadData();
        } catch (Exception ex) {
            Logger.getLogger(ProductMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    /**
     * action when click update button
     *
     * @param evt
     */
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String name = txtPName.getText();//get product name
            String type = txtPType.getText();//get product type
            int price = Integer.parseInt(txtPPrice.getText());//get product price
            String size = txtPSize.getText();//get product size
            String brand = txtPBrand.getText();//get product brand
            int pid = Integer.parseInt(txtPID.getText());
            int t = ptm.findIndexProduct(type);
            int b = pbm.findIndexProductByBrand(brand);
//            int select = tbProduct.getSelectedRow() + 1;//get row number you click
            if (price <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be greater than 0.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
//                for (int i = 0; i <= pro.size(); i++) {
//                    if (i == select) {
                try {
                    System.out.println("" + pid); //display warning message
                    pm.updateProduct(pid, name, t, price, size, b);//update product for database
                    JOptionPane.showMessageDialog(this, "Update product successfully !", "Information", JOptionPane.INFORMATION_MESSAGE);//display message
                    loadData();//load data table
                    tbProduct.updateUI();//reset table
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Can't update product !", "Error", JOptionPane.ERROR_MESSAGE);//display warning message
                }
//                    }
//                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Price can't equal character.", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed
    /**
     * action when click row table
     *
     * @param evt
     */
    private void tbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductMouseClicked
        int select = tbProduct.getSelectedRow();//set number row
        for (int i = 0; i < pro.size(); i++) {
            if (i == select) {
                String a = ptm.findProductName(pro.get(i).getPtype());
                String b = pbm.findProductName(pro.get(i).getBrand());
                txtPID.setText(String.valueOf(pro.get(i).getPid()));//set product ID
                txtPName.setText(pro.get(i).getPname());//set product name
                txtPBrand.setText(b);//set product brand
                txtPPrice.setText(String.valueOf(pro.get(i).getPrice()));//set product price
                txtPSize.setText(pro.get(i).getSize());//set product size
                txtPType.setText(a);//set product type dong nay can sua
            }
        }
        //can't edit 
        txtPName.setEnabled(false);
        txtPBrand.setEnabled(false);
        txtPPrice.setEnabled(false);
        txtPPrice.setEnabled(false);
        txtPSize.setEnabled(false);
        txtPType.setEnabled(false);
        TypeCombo.setEnabled(false);
        BrandCombo.setEnabled(false);

    }//GEN-LAST:event_tbProductMouseClicked
    /**
     * action when click exit button
     *
     * @param evt
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed
    /**
     * list type
     *
     * @param evt
     */
    private void TypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboActionPerformed
        // TODO add your handling code here:
        String a = (String) TypeCombo.getSelectedItem();
        txtPType.setText(a);
    }//GEN-LAST:event_TypeComboActionPerformed
    /**
     * List brand
     *
     * @param evt
     */
    private void BrandComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrandComboActionPerformed
        // TODO add your handling code here:
        String b = (String) BrandCombo.getSelectedItem();
        txtPBrand.setText(b);
    }//GEN-LAST:event_BrandComboActionPerformed
    /**
     * action when click edit button
     *
     * @param evt
     */
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //can edit
        txtPName.setEnabled(true);
        txtPBrand.setEnabled(true);
        txtPPrice.setEnabled(true);
        txtPPrice.setEnabled(true);
        txtPSize.setEnabled(true);
        txtPType.setEnabled(true);
        TypeCombo.setEnabled(true);
        BrandCombo.setEnabled(true);

    }//GEN-LAST:event_btnEditActionPerformed
    /**
     * list size
     *
     * @param evt
     */
    private void SizeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeComboActionPerformed
        // TODO add your handling code here:
        String c = (String) SizeCombo.getSelectedItem();
        txtPSize.setText(c);
    }//GEN-LAST:event_SizeComboActionPerformed
    /**
     * action logout button
     *
     * @param evt
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        new InterfaceShop().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void txtPTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPTypeActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        txtPID.setText("");
        txtPName.setText("");
        txtPBrand.setText("");
        txtPPrice.setText("");
        txtPSize.setText("");
        txtPType.setText("");
    }//GEN-LAST:event_btnClear1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ProductMenu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ProductMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BrandCombo;
    private javax.swing.JComboBox<String> SizeCombo;
    private javax.swing.JComboBox<String> TypeCombo;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductID;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel pnlAll;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlTable;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTextField txtPBrand;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPPrice;
    private javax.swing.JTextField txtPSize;
    private javax.swing.JTextField txtPType;
    // End of variables declaration//GEN-END:variables
}
